import { httpsCallable } from 'firebase/functions';
import { functions } from '../firebase/config';

/**
 * Accept an order and generate OTP via Cloud Function
 * The Cloud Function generates the OTP and stores it in Firestore
 */
export const acceptOrder = async (orderId, orderData) => {
  try {
    // Call Cloud Function to accept order and generate OTP
    const acceptOrderFunction = httpsCallable(functions, 'acceptOrder');
    
    const result = await acceptOrderFunction({
      orderId: orderId
    });

    if (result.data.success) {
      return {
        success: true,
        otp: result.data.otp, // OTP generated by Cloud Function
        expiresAt: result.data.expiresAt,
        message: result.data.message || 'Order accepted and OTP generated successfully'
      };
    } else {
      throw new Error(result.data.message || 'Failed to accept order');
    }
  } catch (error) {
    console.error('Error accepting order:', error);
    
    let errorMessage = error.message;
    if (error.code === 'functions/not-found') {
      errorMessage = 'Cloud Function not found. Please deploy the acceptOrder function.';
    } else if (error.code === 'functions/permission-denied') {
      errorMessage = 'Permission denied. Please check your Firebase rules.';
    } else if (error.code === 'functions/unauthenticated') {
      errorMessage = 'You must be logged in to accept orders.';
    } else if (error.code === 'functions/failed-precondition') {
      errorMessage = error.message || 'Order cannot be accepted in its current state.';
    }
    
    return { success: false, error: errorMessage, errorCode: error.code };
  }
};

/**
 * Reject an order via Cloud Function
 */
export const rejectOrder = async (orderId, reason = '') => {
  try {
    // Call Cloud Function to reject order
    const rejectOrderFunction = httpsCallable(functions, 'rejectOrder');
    
    const result = await rejectOrderFunction({
      orderId: orderId,
      reason: reason
    });

    if (result.data.success) {
      return {
        success: true,
        message: result.data.message || 'Order rejected successfully'
      };
    } else {
      throw new Error(result.data.message || 'Failed to reject order');
    }
  } catch (error) {
    console.error('Error rejecting order:', error);
    
    let errorMessage = error.message;
    if (error.code === 'functions/not-found') {
      errorMessage = 'Cloud Function not found. Please deploy the rejectOrder function.';
    } else if (error.code === 'functions/permission-denied') {
      errorMessage = 'Permission denied. Please check your Firebase rules.';
    } else if (error.code === 'functions/unauthenticated') {
      errorMessage = 'You must be logged in to reject orders.';
    } else if (error.code === 'functions/failed-precondition') {
      errorMessage = error.message || 'Order cannot be rejected in its current state.';
    }
    
    return { success: false, error: errorMessage, errorCode: error.code };
  }
};

/**
 * Verify OTP and mark order as complete via Cloud Function
 */
export const verifyOTPAndCompleteOrder = async (orderId, enteredOTP) => {
  try {
    // Call Cloud Function to verify OTP
    const verifyOTPFunction = httpsCallable(functions, 'verifyOTP');
    
    const result = await verifyOTPFunction({
      orderId: orderId,
      otp: enteredOTP
    });

    if (result.data.success) {
      return {
        success: true,
        message: result.data.message || 'OTP verified successfully. Order marked as completed.'
      };
    } else {
      // OTP verification failed (invalid OTP)
      return {
        success: false,
        error: result.data.message || 'Invalid OTP'
      };
    }
  } catch (error) {
    console.error('Error verifying OTP:', error);
    
    let errorMessage = error.message;
    if (error.code === 'functions/not-found') {
      errorMessage = 'Cloud Function not found. Please deploy the verifyOTP function.';
    } else if (error.code === 'functions/permission-denied') {
      errorMessage = 'Permission denied. Please check your Firebase rules.';
    } else if (error.code === 'functions/unauthenticated') {
      errorMessage = 'You must be logged in to verify OTP.';
    } else if (error.code === 'functions/failed-precondition') {
      errorMessage = error.message || 'Order is not ready for OTP verification yet.';
    } else if (error.code === 'functions/deadline-exceeded') {
      errorMessage = error.message || 'OTP has expired. Please accept the order again to generate a new OTP.';
    } else if (error.code === 'functions/invalid-argument') {
      errorMessage = error.message || 'Invalid OTP format. Please enter a 6-digit number.';
    }
    
    return { success: false, error: errorMessage, errorCode: error.code };
  }
};

/**
 * Get Order OTP (for merchant to view)
 * Useful if merchant needs to see the OTP again
 */
export const getOrderOTP = async (orderId) => {
  try {
    const getOTPFunction = httpsCallable(functions, 'getOrderOTP');
    
    const result = await getOTPFunction({
      orderId: orderId
    });

    if (result.data.success) {
      return {
        success: true,
        otp: result.data.otp,
        expiresAt: result.data.expiresAt,
        isExpired: result.data.isExpired,
        otpVerified: result.data.otpVerified
      };
    } else {
      throw new Error(result.data.message || 'Failed to get order OTP');
    }
  } catch (error) {
    console.error('Error getting order OTP:', error);
    
    let errorMessage = error.message;
    if (error.code === 'functions/not-found') {
      errorMessage = 'Cloud Function not found. Please deploy the getOrderOTP function.';
    } else if (error.code === 'functions/permission-denied') {
      errorMessage = 'Permission denied. Please check your Firebase rules.';
    } else if (error.code === 'functions/failed-precondition') {
      errorMessage = error.message || 'Order must be accepted to view OTP.';
    }
    
    return { success: false, error: errorMessage, errorCode: error.code };
  }
};
